name: vacations_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  badges: ^3.1.2
  percent_indicator: ^4.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.1
  file_picker: ^5.5.0
  intl: ^0.18.1






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Bahij TheSansArabic
      fonts:
        #        - asset: fonts/Bahij_TheSansArabic-ExtraLight.ttf
        - asset: fonts/Bahij_TheSansArabic-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

